// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

var TableNames = struct {
	BookCategories   string
	BookOrder        string
	Books            string
	Discounts        string
	OrderDiscount    string
	Orders           string
	SchemaMigrations string
	Users            string
}{
	BookCategories:   "book_categories",
	BookOrder:        "book_order",
	Books:            "books",
	Discounts:        "discounts",
	OrderDiscount:    "order_discount",
	Orders:           "orders",
	SchemaMigrations: "schema_migrations",
	Users:            "users",
}
