// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("BookCategories", testBookCategoriesUpsert)

	t.Run("Books", testBooksUpsert)

	t.Run("Discounts", testDiscountsUpsert)

	t.Run("Orders", testOrdersUpsert)

	t.Run("SchemaMigrations", testSchemaMigrationsUpsert)

	t.Run("Users", testUsersUpsert)
}
